#steps:
#a,b-> private keys and A,B-> public keys
#1. peer A, and peer B agree publicly on p,g
#2. peer A chooses a, and calculates A = g^a mod p
#3. peer B chooses b, and calculates B = g^b mod p
#4. They exchange A and B

#shared secret calculation:
#5. peer A calculates Ka = B^a mod p
#6. peer B calculates Kb = A^b mod p
#7. therefore Ka = Kb


# Publicly known:
#     p, g
#
# Peer A:
#     private key = a
#     public key  = A = g^a mod p
#
# Peer B:
#     private key = b
#     public key  = B = g^b mod p
#
# Exchange:
#     A ↔ B
#
# Peer A:
#     Ka = B^a mod p
#
# Peer B:
#     Kb = A^b mod p
#
# Result:
#     Ka == Kb


import secrets
import time

def generate_keys(p,g):
    start = time.perf_counter()

    #generate private key:
    private_key = secrets.randbelow(p-2)+1

    #generate public key:
    public_key = pow(g,private_key,p)

    end = time.perf_counter()

    return private_key,public_key,end-start



def generate_shared_secret(private_key, other_public_key, p):
    start = time.perf_counter()

    shared_secret = pow(other_public_key,private_key,p)

    end = time.perf_counter()

    return shared_secret, end - start

def main():
    print("=" * 60)
    print("DIFFIE-HELLMAN KEY EXCHANGE")
    print("=" * 60)

    p = 467
    g = 2

    print("\nPublic parameters:")
    print("p =", p)
    print("g =", g)

    #---------------------------------------
    #Peer A key generation
    # ---------------------------------------

    a, A, a_key_time = generate_keys(p,g)

    print("\nPeer A:")
    print("\nPrivate Key: ",a)
    print("\nPublic Key: ",A)
    print("\nTime taken to generate keys for A: ",a_key_time," seconds")

    # ---------------------------------------
    # Peer B key generation
    # ---------------------------------------

    b, B, b_key_time = generate_keys(p, g)

    print("\nPeer B:")
    print("\nPrivate Key: ", b)
    print("\nPublic Key: ", B)
    print("\nTime taken to generate keys for B: ", b_key_time, " seconds")

    # ---------------------------------------
    #key exchange
    # ---------------------------------------

    Ka, exchange_time_a = generate_shared_secret(a,B,p)
    Kb, exchange_time_b = generate_shared_secret(b,A,p)

    print("\nShared secret generated by Peer A:",
          Ka)

    print("Shared secret generated by Peer B:",
          Kb)

    print("\nPeer A shared secret == Peer B shared secret:",
          Ka == Kb)

    print("\nPeer A key exchange time:",
          exchange_time_a, "seconds")

    print("Peer B key exchange time:",
          exchange_time_b, "seconds")

    print("\nTotal key generation time:",
          a_key_time + b_key_time, "seconds")

    print("Total key exchange time:",
          exchange_time_a + exchange_time_b, "seconds")


main()